#!/usr/bin/env bash
#This script displays content in the current directory in a list format where only part of the name after the first dash is displayed.
#!/usr/bin/env bash
# This script displays the contents of the current directory in a list format
# Only the part of the name after the first dash is displayed

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
